import type { Theme } from './index';
import { hexToHSL } from './utils';

// Définir les couleurs Rosé Pine Moon (15 couleurs officielles)
const rosepineMoonColors: Record<string, string> = {
  base: '#232136',
  surface: '#2a273f',
  overlay: '#393552',
  muted: '#6e6a86',
  subtle: '#908caa',
  text: '#e0def4',
  love: '#eb6f92',
  gold: '#f6c177',
  rose: '#ea9a97',
  pine: '#3e8fb0',
  foam: '#9ccfd8',
  iris: '#c4a7e7',
  'highlight-low': '#2a283e',
  'highlight-med': '#44415a',
  'highlight-high': '#56526e',
};

export const rosepineMoon: Theme = {
  id: 'rosepine-moon',
  name: 'Rosé Pine Moon',
  colors: rosepineMoonColors,
  cssVariables: {
    // Semantic mappings
    '--background': hexToHSL(rosepineMoonColors.base),
    '--foreground': hexToHSL(rosepineMoonColors.text),
    '--card': hexToHSL(rosepineMoonColors.surface),
    '--card-foreground': hexToHSL(rosepineMoonColors.subtle),
    '--popover': hexToHSL(rosepineMoonColors.surface),
    '--popover-foreground': hexToHSL(rosepineMoonColors.subtle),
    '--primary': hexToHSL(rosepineMoonColors.pine),
    '--primary-foreground': hexToHSL(rosepineMoonColors.text),
    '--secondary': hexToHSL(rosepineMoonColors.overlay),
    '--secondary-foreground': hexToHSL(rosepineMoonColors.text),
    '--muted': hexToHSL(rosepineMoonColors.overlay),
    '--muted-foreground': hexToHSL(rosepineMoonColors.muted),
    '--accent': hexToHSL(rosepineMoonColors.iris),
    '--accent-foreground': hexToHSL(rosepineMoonColors.text),
    '--destructive': hexToHSL(rosepineMoonColors.love),
    '--destructive-foreground': hexToHSL(rosepineMoonColors.text),
    '--border': hexToHSL(rosepineMoonColors['highlight-med']),
    '--input': hexToHSL(rosepineMoonColors['highlight-low']),
    '--ring': hexToHSL(rosepineMoonColors.pine),
    '--sidebar': hexToHSL(rosepineMoonColors['highlight-low']),
    // Rosé Pine Moon native colors as CSS variables
    '--love': hexToHSL(rosepineMoonColors.love),
    '--gold': hexToHSL(rosepineMoonColors.gold),
    '--yellow': hexToHSL(rosepineMoonColors.gold),
    '--rose': hexToHSL(rosepineMoonColors.rose),
    '--pine': hexToHSL(rosepineMoonColors.pine),
    '--foam': hexToHSL(rosepineMoonColors.foam),
    '--iris': hexToHSL(rosepineMoonColors.iris),
    '--highlight-low': hexToHSL(rosepineMoonColors['highlight-low']),
    '--highlight-med': hexToHSL(rosepineMoonColors['highlight-med']),
    '--highlight-high': hexToHSL(rosepineMoonColors['highlight-high']),
    '--base': hexToHSL(rosepineMoonColors.base),
    '--surface': hexToHSL(rosepineMoonColors.surface),
    '--overlay': hexToHSL(rosepineMoonColors.overlay),
    '--muted-color': hexToHSL(rosepineMoonColors.muted),
    '--subtle': hexToHSL(rosepineMoonColors.subtle),
    // Catppuccin-compatible variables (mapped to Rosé Pine equivalents)
    '--rosewater': hexToHSL(rosepineMoonColors.subtle),
    '--flamingo': hexToHSL(rosepineMoonColors.rose),
    '--pink': hexToHSL(rosepineMoonColors.love),
    '--mauve': hexToHSL(rosepineMoonColors.iris),
    '--red': hexToHSL(rosepineMoonColors.love),
    '--maroon': hexToHSL(rosepineMoonColors.love),
    '--peach': hexToHSL(rosepineMoonColors.gold),
    '--green': hexToHSL(rosepineMoonColors.foam),
    '--teal': hexToHSL(rosepineMoonColors.foam),
    '--sky': hexToHSL(rosepineMoonColors.foam),
    '--sapphire': hexToHSL(rosepineMoonColors.pine),
    '--blue': hexToHSL(rosepineMoonColors.pine),
    '--lavender': hexToHSL(rosepineMoonColors.iris),
    '--surface-0': hexToHSL(rosepineMoonColors['highlight-low']),
    '--surface-1': hexToHSL(rosepineMoonColors.overlay),
    '--surface-2': hexToHSL(rosepineMoonColors['highlight-high']),
    '--overlay-0': hexToHSL(rosepineMoonColors.muted),
    '--overlay-1': hexToHSL(rosepineMoonColors.subtle),
    '--overlay-2': hexToHSL(rosepineMoonColors.text),
  },
};
