import type { Theme } from './index';
import { hexToHSL } from './utils';

// Définir les couleurs Rosé Pine Moon (15 couleurs officielles)
const rosepineMoonColors: Record<string, string> = {
  base: '#232136',
  surface: '#2a273f',
  overlay: '#393552',
  muted: '#6e6a86',
  subtle: '#908caa',
  text: '#e0def4',
  love: '#eb6f92',
  gold: '#f6c177',
  rose: '#ea9a97',
  pine: '#3e8fb0',
  foam: '#9ccfd8',
  iris: '#c4a7e7',
  'highlight-low': '#2a283e',
  'highlight-med': '#44415a',
  'highlight-high': '#56526e',
  // Catppuccin-compatible keys for xterm.js theme mapping
  rosewater: '#908caa',
  flamingo: '#ea9a97',
  pink: '#eb6f92',
  mauve: '#c4a7e7',
  red: '#eb6f92',
  maroon: '#eb6f92',
  peach: '#f6c177',
  yellow: '#f6c177',
  green: '#9ccfd8',
  teal: '#9ccfd8',
  sky: '#9ccfd8',
  sapphire: '#3e8fb0',
  blue: '#3e8fb0',
  lavender: '#c4a7e7',
  subtext1: '#908caa',
  subtext0: '#6e6a86',
  overlay2: '#e0def4',
  overlay1: '#908caa',
  overlay0: '#6e6a86',
  surface2: '#56526e',
  surface1: '#393552',
  surface0: '#2a283e',
  mantle: '#2a283e',
  crust: '#44415a',
};

export const rosepineMoon: Theme = {
  id: 'rosepine-moon',
  name: 'Rosé Pine Moon',
  colors: rosepineMoonColors,
  configPicker: [
    { key: 'love', hex: rosepineMoonColors.love, label: 'Love' },
    { key: 'iris', hex: rosepineMoonColors.iris, label: 'Iris' },
    { key: 'pine', hex: rosepineMoonColors.pine, label: 'Pine' },
    { key: 'foam', hex: rosepineMoonColors.foam, label: 'Foam' },
    { key: 'gold', hex: rosepineMoonColors.gold, label: 'Gold' },
    { key: 'rose', hex: rosepineMoonColors.rose, label: 'Rose' },
  ],
  cssVariables: {
    // Semantic mappings
    '--background': hexToHSL(rosepineMoonColors.base),
    '--foreground': hexToHSL(rosepineMoonColors.text),
    '--card': hexToHSL(rosepineMoonColors.surface),
    '--card-foreground': hexToHSL(rosepineMoonColors.subtle),
    '--popover': hexToHSL(rosepineMoonColors.surface),
    '--popover-foreground': hexToHSL(rosepineMoonColors.subtle),
    '--primary': hexToHSL(rosepineMoonColors.pine),
    '--primary-foreground': hexToHSL(rosepineMoonColors.text),
    '--secondary': hexToHSL(rosepineMoonColors.overlay),
    '--secondary-foreground': hexToHSL(rosepineMoonColors.text),
    '--muted': hexToHSL(rosepineMoonColors.overlay),
    '--muted-foreground': hexToHSL(rosepineMoonColors.muted),
    '--accent': hexToHSL(rosepineMoonColors.iris),
    '--accent-foreground': hexToHSL(rosepineMoonColors.text),
    '--destructive': hexToHSL(rosepineMoonColors.love),
    '--destructive-foreground': hexToHSL(rosepineMoonColors.text),
    '--border': hexToHSL(rosepineMoonColors['highlight-med']),
    '--input': hexToHSL(rosepineMoonColors['highlight-low']),
    '--ring': hexToHSL(rosepineMoonColors.pine),
    '--sidebar': hexToHSL(rosepineMoonColors['highlight-low']),
    // Rosé Pine Moon native colors as CSS variables
    '--love': hexToHSL(rosepineMoonColors.love),
    '--gold': hexToHSL(rosepineMoonColors.gold),
    '--yellow': hexToHSL(rosepineMoonColors.gold),
    '--rose': hexToHSL(rosepineMoonColors.rose),
    '--pine': hexToHSL(rosepineMoonColors.pine),
    '--foam': hexToHSL(rosepineMoonColors.foam),
    '--iris': hexToHSL(rosepineMoonColors.iris),
    '--highlight-low': hexToHSL(rosepineMoonColors['highlight-low']),
    '--highlight-med': hexToHSL(rosepineMoonColors['highlight-med']),
    '--highlight-high': hexToHSL(rosepineMoonColors['highlight-high']),
    '--base': hexToHSL(rosepineMoonColors.base),
    '--surface': hexToHSL(rosepineMoonColors.surface),
    '--overlay': hexToHSL(rosepineMoonColors.overlay),
    '--muted-color': hexToHSL(rosepineMoonColors.muted),
    '--subtle': hexToHSL(rosepineMoonColors.subtle),
    // Catppuccin-compatible variables (mapped to Rosé Pine equivalents)
    '--rosewater': hexToHSL(rosepineMoonColors.subtle),
    '--flamingo': hexToHSL(rosepineMoonColors.rose),
    '--pink': hexToHSL(rosepineMoonColors.love),
    '--mauve': hexToHSL(rosepineMoonColors.iris),
    '--red': hexToHSL(rosepineMoonColors.love),
    '--maroon': hexToHSL(rosepineMoonColors.love),
    '--peach': hexToHSL(rosepineMoonColors.gold),
    '--green': hexToHSL(rosepineMoonColors.foam),
    '--teal': hexToHSL(rosepineMoonColors.foam),
    '--sky': hexToHSL(rosepineMoonColors.foam),
    '--sapphire': hexToHSL(rosepineMoonColors.pine),
    '--blue': hexToHSL(rosepineMoonColors.pine),
    '--lavender': hexToHSL(rosepineMoonColors.iris),
    '--surface-0': hexToHSL(rosepineMoonColors['highlight-low']),
    '--surface-1': hexToHSL(rosepineMoonColors.overlay),
    '--surface-2': hexToHSL(rosepineMoonColors['highlight-high']),
    '--overlay-0': hexToHSL(rosepineMoonColors.muted),
    '--overlay-1': hexToHSL(rosepineMoonColors.subtle),
    '--overlay-2': hexToHSL(rosepineMoonColors.text),
    // Item highlight (dropdown hover/focus)
    '--item-highlight': '0 0% 100%', // white
  },
};
